name: server
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  grpc: ^3.0.2
  grpc_gen:
    path: ../grpc_gen

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
